import type { SignaturesRepository } from './signatures.repository.js';

export type SignaturesRepositoryPort = Pick<
  SignaturesRepository,
  | 'findPendingQueue'
  | 'findActiveFlowsQueue'
  | 'countActiveFlowsQueue'
  | 'findContractByIdForCompany'
  | 'findActiveFlowForContract'
  | 'createSignatureRequest'
  | 'updateContractStatus'
  | 'findByToken'
  | 'findSignerByToken'
  | 'signContractTransaction'
  | 'findHistoryForContract'
  | 'findFlowByIdForCompany'
  | 'findLatestFlowForContract'
  | 'findSignedDocument'
  | 'findFrozenDocument'
  | 'findSignerByTokenWithDocuments'
  | 'findSignatureAppliedEvent'
  | 'getLastEventHash'
  | 'recordEvent'
  | 'createFlowWithSigners'
  | 'markSignerViewed'
  | 'recordConsent'
  | 'applySignature'
  | 'cancelFlow'
  | 'saveContractDocument'
  | 'createUploadRecord'
  | 'findUploadById'
  | 'createSignerOtp'
  | 'findLatestOtp'
  | 'markOtpVerified'
  | 'hasVerifiedOtp'
>;
